import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Header from "../components/Header";
import Slider from "../components/Slider";
import DominicanRepublic from "../assets/DominicanRepublic.jpg";
import Cuba from "../assets/Cuba.jpg";
import Mexico from "../assets/Mexico.jpg";
import axios from "axios";
import { useEffect, useState } from "react";
import Country from "../components/country";
import Searcher from "../components/searcher";
import Footer from "../components/Footer";
import { AiFillStar } from "react-icons/ai";

import "react-date-range/dist/styles.css"; // main css file
import "react-date-range/dist/theme/default.css"; // theme css file
import YourAgency from "../components/yourAgency";
import OurReasons from "../components/ourReasons";

const inter = Inter({ subsets: ["latin"] });

// const API_URL = process.env.NEXT_PUBLIC_API_URL;

export default function Home() {
  const API_URL = "http://localhost:5005";

  const [holidays, setHolidays] = useState([]);
  const [filteredHolidays, setFilteredHolidays] = useState(holidays);

  useEffect(() => {
    const source = axios.CancelToken.source();

    axios
      .get(`${API_URL}/holidays`)
      .then((response) => {
        setHolidays(response.data);
      })
      .catch((error) => {
        console.log(error);
      });
  }, []);

  console.log(holidays);

  // const [state, setState] = useState([
  //   {
  //     startDate: new Date(),
  //     endDate: null,
  //     key: 'selection'
  //   }
  // ]);
  // const [showPicker, setShowPicker] = useState(false);
  // const [selectCity, setSelectCity] = useState("");

  // useEffect(() => {
  //   setSelectCity(
  //     holidays.filter((holiday) => {
  //       console.log(holiday.city);
  //       let showCity = true;
  //       return showCity && (selectCity === "" || holiday.city.toLowerCase().includes(selectCity.toLowerCase()));
  //     })
  //   );
  // }, [selectCity]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Slider />
        <Searcher
          holidays={holidays}
          setFilteredHolidays={setFilteredHolidays}
        />
      
        <div className="flex flex-col mx-20 mb-28">
          <div className="my-20">
            <h1 className="font-medium uppercase text-3xl text-center">
              Best of Dominican Republic - All Inclusive
            </h1>
          </div>
          <div className="flex justify-center gap-4">
            <Country />
           
            <div className="flex-1 grid grid-rows-2 grid-cols-2 gap-4">
              {holidays
                .filter(
                  (holiday) => holiday.destination === "Dominican Republic"
                )
                .slice(0, 4)
                .map((holiday, index) => {
                  const randomIndex = Math.floor(
                    Math.random() *
                      holidays.filter(
                        (holiday) =>
                          holiday.destination === "Dominican Republic"
                      ).length
                  );
                  const randomHoliday = holidays.filter(
                    (holiday) => holiday.destination === "Dominican Republic"
                  )[randomIndex];

                  return (
                    <div className="overflow-hidden shadow-lg" key={index}>
                      <Image
                        className="w-full h-1/2 object-cover"
                        src={randomHoliday.imageURL}
                        width={500}
                        height={500}
                        alt="Dominican Republic"
                      />
                      <div className="px-6 py-8">
                        <div className="flex text-[#003265] text-[1rem] mb-2">
                          <p>{randomHoliday.destination}</p>
                        </div>
                        <div>
                          <p className="text-[#003265] font-bold">
                            {randomHoliday.hotel}
                          </p>
                          <div className="flex my-2">
                            {Array.from(
                              { length: randomHoliday.number_of_stars },
                              (_, i) => (
                                <AiFillStar
                                  key={i}
                                  className="text-[#FFCA00]"
                                />
                              )
                            )}
                          </div>
                        </div>
                        <div>
                          <p className="font-light text-sm">9 Days</p>
                        </div>
                        <div className="mt-10">
                          <p className="font-bold text-right text-xl">
                            {randomHoliday.price} €
                          </p>
                        </div>
                      </div>
                    </div>
                  );
                })}
            </div>
          </div>

          <div className="my-20">
            <h1 className="font-medium uppercase text-3xl text-center">
              Best of Cuba - All Inclusive
            </h1>
          </div>
          <div className="flex gap-4">
            <div className="flex-1 grid grid-rows-2 grid-cols-2 gap-4 ">
              {holidays
                .filter((holiday) => holiday.destination === "Cuba")
                .slice(0, 4)
                .map((holiday, index) => {
                  const randomIndex = Math.floor(
                    Math.random() *
                      holidays.filter(
                        (holiday) => holiday.destination === "Cuba"
                      ).length
                  );
                  const randomHoliday = holidays.filter(
                    (holiday) => holiday.destination === "Cuba"
                  )[randomIndex];

                  return (
                    <div className="overflow-hidden shadow-lg" key={index}>
                      <Image
                        className="w-full h-1/2 object-cover"
                        src={randomHoliday.imageURL}
                        width={500}
                        height={500}
                        alt="Dominican Republic"
                      />
                      <div className="px-6 py-8">
                        <div className="flex text-[#003265] text-[1rem] mb-2">
                          <p>{randomHoliday.destination}</p>
                        </div>
                        <div>
                          <p className="text-[#003265] font-bold">
                            {randomHoliday.hotel}
                          </p>
                          <div className="flex my-2">
                            {Array.from(
                              { length: randomHoliday.number_of_stars },
                              (_, i) => (
                                <AiFillStar
                                  key={i}
                                  className="text-[#FFCA00]"
                                />
                              )
                            )}
                          </div>
                        </div>
                        <div>
                          <p className="font-light text-sm">9 Days</p>
                        </div>
                        <div className="mt-10">
                          <p className="font-bold text-right text-xl">
                            {randomHoliday.price} €
                          </p>
                        </div>
                      </div>
                    </div>
                  );
                })}
            </div>
            <div className="flex flex-1">
              <div className="overflow-hidden shadow-lg w-full">
                <Image
                  className="w-full h-1/2 object-cover"
                  src={Cuba}
                  alt="Cuba"
                />
                <div className="px-6 bg-[#A7E0F9] h-full">
                  <div className="py-28">
                    <div className="font-bold text-[#003265] uppercase text-[3rem] mb-2">
                      Cuba
                    </div>
                    <div>
                      <p className="text-[#003265] text-base">
                        Timeworn but magnificent, dilapidated but dignified, fun
                        yet maddeningly frustrating – Cuba is a country of rich
                        dichotomies, and indefinable magic.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="my-20">
            <h1 className="font-medium uppercase text-3xl text-center">
              Best of Mexico - All Inclusive
            </h1>
          </div>
          <div className="flex justify-center gap-4">
            <div className="flex flex-1">
              <div className="overflow-hidden shadow-lg w-full">
                <Image
                  className="w-full h-1/2 object-cover"
                  src={Mexico}
                  alt="Mexico"
                />
                <div className="px-6 bg-[#FFCA00] h-full">
                  <div className="py-28">
                    <div className="font-bold text-[#003265] uppercase text-[3rem] mb-2">
                      Mexico
                    </div>
                    <div>
                      <p className="text-[#003265] text-base">
                        Mexico is a great mosaic that combines beautiful natural
                        settings, cities with pre-Hispanic, colonial and modern
                        heritage, a wide variety of exquisite delicacies that
                        delight palates, and fascinating traditions that
                        captivate the visitor. From the beach to the mountains,
                        from the desert to the jungle, from the archaeological
                        zone to the vibrant cities, from sweet to spicy flavors,
                        from relaxing to the happy of its parties, Mexico has
                        everything that tourists are looking for, which is well
                        received by the warmth of its people. Mexico has 32
                        states to fall in love with.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex-1 grid grid-rows-2 grid-cols-2 gap-4">
              {holidays
                .filter((holiday) => holiday.destination === "Mexico")
                .slice(0, 4)
                .map((holiday, index) => {
                  const randomIndex = Math.floor(
                    Math.random() *
                      holidays.filter(
                        (holiday) => holiday.destination === "Mexico"
                      ).length
                  );
                  const randomHoliday = holidays.filter(
                    (holiday) => holiday.destination === "Mexico"
                  )[randomIndex];

                  return (
                    <div className="overflow-hidden shadow-lg" key={index}>
                      <Image
                        className="w-full h-1/2 object-cover"
                        src={randomHoliday.imageURL}
                        width={500}
                        height={500}
                        alt="Dominican Republic"
                      />
                      <div className="px-6 py-8">
                        <div className="flex text-[#003265] text-[1rem] mb-2">
                          <p>{randomHoliday.destination}</p>
                        </div>
                        <div>
                          <p className="text-[#003265] font-bold">
                            {randomHoliday.hotel}
                          </p>
                          <div className="flex my-2">
                            {Array.from(
                              { length: randomHoliday.number_of_stars },
                              (_, i) => (
                                <AiFillStar
                                  key={i}
                                  className="text-[#FFCA00]"
                                />
                              )
                            )}
                          </div>
                        </div>
                        <div>
                          <p className="font-light text-sm">9 Days</p>
                        </div>
                        <div className="mt-10">
                          <p className="font-bold text-right text-xl">
                            {randomHoliday.price} €
                          </p>
                        </div>
                      </div>
                    </div>
                  );
                })}
            </div>
          </div>
        </div>
        <div className=" bg-[#A6E0F8] py-32 px-40">
          <div className="flex justify-center mb-20">
            <h2 className="text-[#003265] uppercase text-3xl">
              The reasons of why your holidays should be with us
            </h2>
          </div>
          <OurReasons />
        </div>
        <YourAgency />
        <Footer />
      </main>
    </>
  );
}
